WSS/urls.py
from django.conf.urls import url, include

from WSS.views import HomeView, SeminarsListView, WorkshopsListView, StaffListView, \
    GalleryImageView, GalleryVideoView, \
    ScheduleView

year_urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^seminars/$', SeminarsListView.as_view(), name='seminars-list'),
    url(r'^workshops/$', WorkshopsListView.as_view(), name='workshops-list'),
    url(r'^staff/$', StaffListView.as_view(), name='staff-list'),
    url(r'^gallery/images/$', GalleryImageView.as_view(), name='gallery-image'),
    url(r'^gallery/videos/$', GalleryVideoView.as_view(), name='gallery-video'),
    url(r'^schedule/$', ScheduleView.as_view(), name='schedule'),
]

urlpatterns = [
    url(r'^(?P<year>\d{4})/', include(year_urlpatterns)),
    url(r'^$', HomeView.as_view(), name='home'),
]

WSS_Site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from WSS_Site.error_handler_views import Handler404View

urlpatterns = [
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
                  url(r'^admin-of-wss/', admin.site.urls),
                  url(r'^', include('WSS.urls', namespace='wss')),
                  url(r'^', include('events.urls', namespace='events')),
                  url(r'^', include('people.urls', namespace='people')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'WSS Administration'
admin.site.site_title = 'WSS Administration'

handler404 = Handler404View.as_view()

people/urls.py
from django.conf.urls import url

from people.views import CreatorsListView

urlpatterns = [
    url(r'^creators/$', CreatorsListView.as_view(), name='creators-list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load date_tags %}
{% load human_tags %}

<head>
    <!-- Basic Page Needs ================================================== -->
    <meta charset="utf-8">

    <!-- Mobile Specific Metas ================================================== -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">

    <!-- Site Title -->
    <title>{% block title %}Winter Seminar Series{% endblock %}</title>

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

    <!-- CSS
       ================================================== -->
    <!-- Bootstrap -->
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
    <!--&lt;!&ndash; Template styles&ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}?v=3.5.3">-->
    <!--&lt;!&ndash; Responsive styles&ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/responsive.css' %}?v=1.4.2">-->
    <!--&lt;!&ndash; FontAwesome &ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">-->
    <!--&lt;!&ndash; Animation &ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/animate.css' %}">-->
    <!--&lt;!&ndash; Colorbox &ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/colorbox.css' %}">-->
    <!--&lt;!&ndash; Plyr &ndash;&gt;-->
    <!--<link rel="stylesheet" href="{% static 'css/plyr.css' %}">-->

    <!-- All css files combined into one sigle file -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <!-- Template styles-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=3.5.3">


    <!-- Map -->
    <!--<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE  9]>
    <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
    <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
    <![endif]-->

</head>

<body>
<div class="body-inner">
    {% block header %}
        <!-- Header start -->
        <header id="header" class="header-dark">
            <div class="container">
                <div class="row">
                    <div class="site-nav-inner">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <nav class="collapse navbar-collapse navbar-responsive-collapse pull-right">
                            <ul class="nav navbar-nav">
                                {% block navbar_items %}
                                    <li><a href="{% url 'wss:home' %}">Home</a></li>
                                    <!-- Home li end -->
                                    <li class="header-ticket">
                                        <a href="{% url 'wss:home' %}" class="ticket-btn btn-primary">Visit the last
                                            seminar page</a>
                                    </li>
                                {% endblock %}
                                <!-- Register li end -->
                            </ul>
                            <!--/ Nav ul end -->
                        </nav>
                        <!--/ Collapse end -->
                    </div>
                    <!--/ Site nav inner end -->
                </div>
                <!--/ Row end -->
            </div>
            <!--/ Container end -->
        </header>
        <!--/ Header end -->
    {% endblock %}

    {% block content %}
    {% endblock %}

    <footer id="footer" class="footer text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-menu">
                        <ul class="nav unstyled">
                            {% block footer_menu_items %}
                                <li><a href="{% url 'wss:home' %}">Home</a></li>
                                <li><a href="{% url 'wss:home' %}">Visit the Latest seminar page</a></li>
                            {% endblock %}
                        </ul>
                        {% if past_years %}
                        <span>Past seminars archive:</span>
                        <ul class="nav fa">
                            {% for past_year in past_years %}
                                <li><a href="{% url 'wss:home' past_year %}">{{ past_year }}</a></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    <!-- Footer menu end -->
                    <div class="footer-logo">
                        <a href="{{ SITE_URL }}"><img src="{% static 'images/WSS-2018-logo-white.png' %}" alt="footer logo" width="100"/></a>
                        <a href="http://ssc.ce.sharif.edu"><img src="{% static 'images/SSC-logo-white.png' %}" alt="footer logo" width="100"/></a>
                    </div>
                    <div class="footer-social">
                        <ul>
                            {% for external_link in external_links %}
                                <li><a href="{{ external_link.url }}"><i class="fa fa-{{ external_link.type }}"></i></a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- Footer social end -->
                    <div class="copyright-info">
                  <span>This website is created by <a href="{% url 'people:creators-list' %}">Moazzam Team</a>.<br>
                  Copyright © 2015-2017 WSS. All Rights Reserved.</span>
                    </div>
                    <!-- Copyright info end -->
                </div>
                <!-- Content col end -->
            </div>
            <!-- Content row end -->
        </div>
        <!-- Container end -->

        <!--<div id="back-to-top" data-spy="affix" data-offset-top="10" class="header affix"></div>-->
    </footer>
    <!-- Footer end -->

    <!-- Javascript Files
       ================================================== -->
    <!--&lt;!&ndash; initialize jQuery Library &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>-->
    <!--&lt;!&ndash; Bootstrap jQuery &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>-->
    <!--&lt;!&ndash; Counter &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/jquery.counterup.min.js' %}"></script>-->
    <!--&lt;!&ndash; Countdown &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/jquery.jCounter.js' %}"></script>-->
    <!--&lt;!&ndash; Waypoints &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/waypoints.min.js' %}"></script>-->
    <!--&lt;!&ndash; Color box for Popup&ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/jquery.colorbox.js' %}"></script>-->
    <!--&lt;!&ndash; Smoothscroll &ndash;&gt;-->
    <!--<script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>-->

    <!--&lt;!&ndash; Plyr &ndash;&gt;-->
    <!--<script src="{% static 'js/plyr.js' %}"></script>-->
    <!--<script>plyr.setup();</script>-->

    <!-- All js files combined into one file -->
    <script type="text/javascript" src="{% static 'js/all.min.js' %}"></script>

    <!-- Template custom -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}?v=3"></script>


</div>
<!-- Body inner end -->
</body>
</html>

templates/wssbase.html
{% extends 'base.html' %}
{% block title %}{{ wss }}{% endblock %}

{% block navbar_items %}
    <li><a href="{% url 'wss:home' wss.year %}">{{ wss }}</a></li>
    <!-- Home li end -->
    <li><a href="{% url 'wss:seminars-list' wss.year %}">Speakers</a></li>
    <!-- Speakers li end -->
    {% if wss.workshops.count %}
        <li><a data-scroll href="{% url 'wss:workshops-list' wss.year %}">Workshops</a></li>
    {% endif %}
    <li><a href="{% url 'wss:schedule' wss.year %}">Schedule</a></li>
    <!-- Schedule li end -->
    <li><a href="{% url 'wss:staff-list' wss.year %}">Staff</a></li>
    <!-- Staff li end -->
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gallery <i class="fa fa-angle-down"></i></a>
        <ul class="dropdown-menu menu-center" role="menu">
            <li><a href="{% url 'wss:gallery-image' wss.year %}">Images</a></li>
            <li><a href="{% url 'wss:gallery-video' wss.year %}">Videos</a></li>
        </ul>
    </li>
    <!-- Gallery li end -->
    {% if wss.is_active %}
        {% if wss.registration_link %}
            <li class="header-ticket">
                <a class="ticket-btn btn-primary" href="{{ wss.registration_link }}">Register</a>
            </li>
        {% endif %}
    {% else %}
        <li class="header-ticket">
            <a href="{% url 'wss:home' %}" class="ticket-btn btn-primary">Visit the Latest seminar page</a>
        </li>
    {% endif %}
{% endblock %}

{% block footer_menu_items %}
    <li><a href="{% url 'wss:home' wss.year %}">Home</a>
    </li>
    {% if wss.is_active %}
        {% if wss.registration_link %}
            <li class="header-ticket">
            <li><a href="{{ wss.registration_link }}">Register</a>
            </li>
        {% endif %}
    {% else %}
        <li><a href="{% url 'wss:home' %}">Visit the Latest seminar page</a></li>
    {% endif %}
{% endblock %}