WSS/urls.py
from django.conf.urls import url, include

from WSS.views import HomeView, SeminarsListView, WorkshopsListView, StaffListView, \
    GalleryImageView, GalleryVideoView, \
    ScheduleView

year_urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^seminars/$', SeminarsListView.as_view(), name='seminars-list'),
    url(r'^workshops/$', WorkshopsListView.as_view(), name='workshops-list'),
    url(r'^staff/$', StaffListView.as_view(), name='staff-list'),
    url(r'^gallery/images/$', GalleryImageView.as_view(), name='gallery-image'),
    url(r'^gallery/videos/$', GalleryVideoView.as_view(), name='gallery-video'),
    url(r'^schedule/$', ScheduleView.as_view(), name='schedule'),
]

urlpatterns = [
    url(r'^(?P<year>\d{4})/', include(year_urlpatterns)),
    url(r'^$', HomeView.as_view(), name='home'),
]

WSS_Site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from WSS_Site.error_handler_views import Handler404View

urlpatterns = [
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
                  url(r'^admin-of-wss/', admin.site.urls),
                  url(r'^', include('WSS.urls', namespace='wss')),
                  url(r'^', include('events.urls', namespace='events')),
                  url(r'^', include('people.urls', namespace='people')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'WSS Administration'
admin.site.site_title = 'WSS Administration'

handler404 = Handler404View.as_view()

events/urls.py
from django.conf.urls import url

from events.views import SeminarView, WorkshopView

urlpatterns = [
    url(r'seminar/(?P<pk>\d+)/$', SeminarView.as_view(), name='seminar'),
    url(r'workshop/(?P<pk>\d+)/$', WorkshopView.as_view(), name='workshop'),
]

WSS/models.py
from django.db import models
from django.utils.safestring import mark_safe
from pip._vendor import requests
from sorl.thumbnail import ImageField

from events.models import Workshop, Seminar


class WSS(models.Model):
    year = models.PositiveSmallIntegerField()
    description = models.TextField()
    registration_link = models.URLField(null=True, blank=True)
    proposal_link = models.URLField(null=True, blank=True)
    participants_count_link = models.URLField(null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    main_clip = models.OneToOneField(to='Clip', null=True, blank=True, related_name='+')
    main_image = models.OneToOneField(to='Image', null=True, blank=True, related_name='+')

    class Meta:
        ordering = ('-year',)
        verbose_name = 'Winter Seminar Series'
        verbose_name_plural = 'Winter Seminar Series'

    def __str__(self):
        return 'WSS {}'.format(self.year)

    @property
    def main_image_url(self):
        if not self.main_image:
            return None
        return self.main_image.image.url

    @property
    def main_clip_url(self):
        if not self.main_clip:
            return None
        return self.main_clip.clip.url

    @property
    def workshops(self):
        return Workshop.objects.filter(wss=self)

    @property
    def seminars(self):
        return Seminar.objects.filter(wss=self)

    @property
    def staff_count(self):
        return len(set().union(
            *[holding_team.staff.values_list('pk') for holding_team in self.holding_teams.all()]
        ))

    @property
    def keynote_seminars(self):
        return self.seminars.filter(is_keynote=True)

    @property
    def non_keynote_seminars(self):
        return self.seminars.filter(is_keynote=False)

    @property
    def main_sponsorships(self):
        return self.sponsorships.filter(is_main=True)

    @property
    def not_main_sponsorships(self):
        return self.sponsorships.filter(is_main=False)

    @classmethod
    def active_wss(cls):
        return cls.objects.first()

    @property
    def is_active(self):
        return self.pk == WSS.active_wss().pk

    @property
    def participants_count(self):
        try:
            return requests.get(self.participants_count_link).content
        except:
            return 0


class Clip(models.Model):
    wss = models.ForeignKey(to='WSS', related_name='clips', verbose_name='WSS')
    clip = models.FileField(upload_to='clips/')

    def __str__(self):
        return 'Clip of {}'.format(self.wss)


class Image(models.Model):
    wss = models.ForeignKey(to='WSS', related_name='images', verbose_name='WSS')
    image = ImageField(upload_to='images/')

    def __str__(self):
        return 'Image of {}'.format(self.wss)


class Sponsor(models.Model):
    name = models.CharField(max_length=70)
    logo = models.ImageField(upload_to='logos/')
    url = models.URLField()

    def __str__(self):
        return self.name

    def logo_tag(self):
        if not self.logo:
            return None
        return mark_safe('<img src={} width=40 height=40>'.format(self.logo.url))

    logo_tag.short_description = 'logo'


class Sponsorship(models.Model):
    wss = models.ForeignKey(to='WSS', related_name='sponsorships')
    sponsor = models.ForeignKey(to=Sponsor, related_name='sponsorships')
    is_main = models.BooleanField()

    def __str__(self):
        return self.sponsor.name

    @property
    def logo_url(self):
        if not self.sponsor.logo:
            return None
        return self.sponsor.logo.url


class ExternalLink(models.Model):
    type = models.CharField(max_length=40)
    url = models.URLField()

    def __str__(self):
        return '{}: {}'.format(self.type, self.url)

WSS/views.py
from itertools import groupby

from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView

from WSS.mixins import FooterMixin, WSSWithYearMixin
from WSS.models import WSS


class HomeView(FooterMixin, DetailView):
    template_name = 'WSS/home.html'
    context_object_name = 'wss'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selected_seminars'] = self.object.non_keynote_seminars.order_by('?')[:8]
        return context

    def get_object(self, queryset=None):
        if 'year' in self.kwargs:
            return get_object_or_404(WSS, year=int(self.kwargs['year']))
        return WSS.objects.first()


class SeminarsListView(FooterMixin, DetailView):
    template_name = 'WSS/seminars_list.html'
    model = WSS
    context_object_name = 'wss'

    def get_object(self, queryset=None):
        return get_object_or_404(WSS, year=int(self.kwargs['year']))


class WorkshopsListView(FooterMixin, DetailView):
    template_name = 'WSS/workshops_list.html'
    model = WSS
    context_object_name = 'wss'

    def get_object(self, queryset=None):
        return get_object_or_404(WSS, year=int(self.kwargs['year']))


class StaffListView(FooterMixin, DetailView):
    template_name = 'WSS/staff_list.html'
    model = WSS
    context_object_name = 'wss'

    def get_object(self, queryset=None):
        return get_object_or_404(WSS, year=int(self.kwargs['year']))


class GalleryImageView(FooterMixin, WSSWithYearMixin, DetailView):
    template_name = 'WSS/gallery_images.html'


class GalleryVideoView(FooterMixin, WSSWithYearMixin, DetailView):
    template_name = 'WSS/gallery_videos.html'


class ScheduleView(FooterMixin, WSSWithYearMixin, DetailView):
    template_name = 'WSS/schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        wss = self.object
        all_events = wss.events.filter(start_time__isnull=False)

        context['pre_wss_events'] = all_events.filter(start_time__date__lt=wss.start_date)
        main_events = all_events.exclude(start_time__date__lt=wss.start_date)

        # Important: I assumed that events with same start_time will have same end_time
        events_by_day = groupby(groupby(main_events, lambda event: event.start_time),
                                lambda group: group[0].date())

        # Surprising bug made me do this! I have know idea why I should reiterate events_by_day!
        context['events_by_day'] = []
        for date, events_by_time in events_by_day:
            print(date)
            _events_by_time = []
            for time, events in events_by_time:
                _events_by_time.append((time, list(events)))  # OMG! casting to list is important!!
            context['events_by_day'].append((date, _events_by_time))
        return context

WSS/templates/WSS/gallery_images.html
{% extends 'wssbase.html' %}
{% load static %}
{% load thumbnail %}
{% load human_tags %}

{% block title %}{{ wss }} Images {% endblock %}

{% block content %}
    <section id="main-container" class="main-container">
        <div class="container">
            <div class="row text-center">
                <h2 class="section-title">{{ wss }}</h2>
                <h3 class="section-sub-title title"> Photo Gallery </h3>
            </div>
            <div class="row">
                {% for item in wss.images.all %}
                    <div id="gallery">
                        <div class="col-md-4 col-sm-6 col-xs-12">

                                <div class="gallery-container" style="width: 300px">
                                    <a class="gallery-popup" href="{{ item.image.url }}">
                                    {% thumbnail item.image "300x300" crop="center" as im %}
                                        <img class="img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                    {% endthumbnail %}
                                    <span class="gallery-icon"><i class="fa fa-search"></i></span>
                                    </a>
                                </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

WSS/templates/WSS/gallery_videos.html
{% extends 'wssbase.html' %}
{% load static %}
{% load thumbnail %}
{% load human_tags %}

{% block title %}{{ wss }} Videos {% endblock %}

{% block content %}
    <section id="main-container" class="main-container">
        <div class="container">
            <div class="row text-center">
                <h2 class="section-title">{{ wss }}</h2>
                <h3 class="section-sub-title title"> Video Gallery </h3>
            </div>
            <div class="row">
                {% for item in wss.clips.all %}

                    <div class="col-xs-12 col-sm-12 col-md-6 text-center" style="margin-bottom: 20px">
                         <div class="intro-video">
                            <img class="img-responsive" src="{% static 'images/intro-video.jpg' %}" alt="" />
                            <a class="popup" href="{{ item.clip.url }}">
                               <div class="video-icon">
                                  <i class="fa fa-play"></i>
                               </div>
                            </a>
                         </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

WSS/templates/WSS/schedule.html
{% extends 'wssbase.html' %}
{% load date_tags %}

{% block content %}

	<section id="main-container" class="main-container" style="padding: 40px 0 0 0">

		{% if pre_wss_events.count %}
		<div class="schedule-content  pattern-bg ">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="row text-center">
							<h3 class="section-sub-title">Pre-{{ wss }} Events</h3>
						</div><!--/ Title row end -->

						<div class="schedule-listing">
						{% for event in pre_wss_events %}

							<span class="schedule-slot-time">
								{{event.start_time.date }}<br>{% time_string event.start_time %} - {% time_string event.end_time %}
							</span>
							<div class="schedule-slot-info">

								<div class="schedule-slot-info-content">
									<h3 class="schedule-slot-speaker-name">{{ event.speaker }}</h3>
									{% if event.seminar %}
										<a href="{% url 'events:seminar' event.pk %}">
									{% elif event.workshop %}
										<a href="{% url 'events:workshop' event.pk %}">
									{% endif %}
									<h3 class="schedule-slot-title">{{ event.title }}</h3>
									{% if event.seminar %}
										</a>
									{% elif event.workshop %}
										</a>
									{% endif %}
									{% if event.venue %}
										<span class="schedule-slot-desc" data-toggle="tooltip" title="{{ event.venue.address }}">{{ event.venue }}</span>
									{% endif %}

								</div><!--Info content end -->

							</div><!-- Slot info end -->

							{% if not forloop.last %}
							<br><br>
							{% endif %}
						{% endfor %}
						</div><!-- Slot listing 1 end -->

					</div><!-- Col end -->
				</div><!-- Content row 1 end -->
			</div><!-- Container 2 end -->
		</div><!-- schedule-content 1 end -->

		{% endif %}
		<div class="gap-60"></div>

		<div class="container">
			<div class="row text-center">
				<h3 class="section-sub-title">{{ wss }} Schedule</h3>
			</div><!--/ Title row end -->
		</div><!-- Container 1 end -->

		{% for day, events_by_time in events_by_day %}
			<div class="schedule-content {% if forloop.counter|divisibleby:2 %} pattern-bg {% endif %}">
				<div class="container">
					<div class="row">
						<div class="col-md-12">

							<h2 class="schedule-date">Day {{ forloop.counter }} / {% date_string day %}</h2>

							{% for _, events in events_by_time %}

								<div class="schedule-listing {% if forloop.counter|divisibleby:2 %} bg {% endif %}">
								{% for event in events %}

									{% if forloop.counter == 1 %}
										{% if day %}
											<span class="schedule-slot-time">{% time_string event.start_time %} - {% time_string event.end_time %}</span>
										{% endif %}
										<div class="schedule-slot-info">
									{% endif %}

											<div class="schedule-slot-info-content">
												<h3 class="schedule-slot-speaker-name">{{ event.speaker }}</h3>
												{% if event.seminar %}
													<a href="{% url 'events:seminar' event.pk %}">
												{% elif event.workshop %}
													<a href="{% url 'events:workshop' event.pk %}">
												{% endif %}
												<h3 class="schedule-slot-title">{{ event.title }}</h3>
												{% if event.seminar %}
													</a>
												{% elif event.workshop %}
													</a>
												{% endif %}
												{% if event.venue %}
													<span class="schedule-slot-desc" data-toggle="tooltip" title="{{ event.venue.address }}">{{ event.venue }}</>
												{% endif %}

											</div><!--Info content end -->

									{% if not forloop.last %}
									<br>
									{% endif %}

								{% endfor %}
								</div><!-- Slot info end -->

								</div><!-- Slot listing 1 end -->


							{% endfor %}

						</div><!-- Col end -->
					</div><!-- Content row 1 end -->
				</div><!-- Container 2 end -->
				<div class="gap-60"></div>
			</div><!-- schedule-content 1 end -->

		{% empty %}
			<div class="row text-center">
				<h3 class="schedule-date">TBD</h3>
			</div>
		{% endfor %}

	</section><!-- Main container end -->

{% endblock %}

WSS/templates/WSS/seminars_list.html
{% extends 'wssbase.html' %}
{% load static %}
{% load date_tags %}
{% load human_tags %}

{% block title %}{{ wss }} speakers{% endblock %}
{% block content %}
   <section id="ts-speakers" class="ts-speakers gradient-bg">
      <div class="container">
         <div class="row text-center">
            {% if wss.keynote_seminars.count %}
            <h3 class="section-sub-title title-white">Keynote Speakers</h3>
            {% endif %}
         </div>

         <!--/ Title row end -->
         <div class="row">
            {% for seminar in wss.keynote_seminars %}
            <div class="col-xs-12 col-sm-6 col-md-3">
               {% render_human seminar.speaker subtitle=seminar.speaker.short_bio url=seminar.get_absolute_url %}
            </div>
            {% endfor %}
         </div>
         <br>

         <div class="row text-center">
            <h3 class="section-sub-title title-white">Speakers</h3>
         </div>
            {% for seminar in wss.non_keynote_seminars %}
         <div class="col-xs-12 col-sm-6 col-md-3">
            {% render_human seminar.speaker subtitle=seminar.speaker.short_bio url=seminar.get_absolute_url %}
         </div>
            {% endfor %}
      </div>

      <!-- Content row 2 end -->

      <!--/ Container end -->
   </section>
   <!-- Speakers end -->
   <section class="venu-map no-padding">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-6">
            <div class="bottom-contact white">
               <h4 class="white">Organizer info</h4>
                  <p>The event is held by the <a href="http://ssc.ce.sharif.edu">Student Scientific
                  Chapter (SSC)</a> of <a href="http://ce.sharif.edu">Computer Engineering Department</a>
                  of <a href="http://sharif.edu">Sharif University of Technology</a>
               </p>
               <br>
               <h4 class="white">Venue Details</h4>
               <div class="contact-info">
                  <div class="contact-info-box">
                     <i class="fa fa-map-marker">&nbsp;</i>
                     <div class="contact-info-box-content">
                        <h5 class="white">Address: </h5>
                        <p>Sharif University of Technology, Azadi Street, Distinct 2, Tehran, Iran</p>
                     </div>
                  </div>
                  <div class="contact-info-box">
                     <i class="fa fa-envelope-o">&nbsp;</i>
                     <div class="contact-info-box-content">
                        <h5 class="white">Email: </h5>
                        <p>wss@ce.sharif.edu</p>
                     </div>
                  </div>
                  <div class="contact-info-box">
                     <i class="fa fa-phone">&nbsp;</i>
                     <div class="contact-info-box-content">
                        <h5 class="white">Phone: </h5>
                        <p>+98(021) 66 16 57 81</p>
                     </div>
                  </div>
               </div>
               <!-- Contact info end -->
            </div>
            <!-- Contact form div end -->
         </div>
         <!-- Col end -->
         <div class="col-md-6">
            <div id="map" class="map-bottom"></div>
            <!-- Google Map -->
         </div>
         <!-- Col end -->
      </div>
      <!-- Content row end -->
   </div>
   <!-- Container end -->
</section>
<!-- Map end -->
{% endblock %}

WSS/templates/WSS/staff_list.html
{% extends 'wssbase.html' %}
{% load static %}
{% load date_tags %}
{% load human_tags %}

{% block title %}{{ wss }} staff{% endblock %}
{% block content %}
   <section id="ts-speakers" class="ts-speakers">
      <div class="container">

         <!--/ Title row end -->
            {% for holding_team in wss.holding_teams.all %}
               <div class="row">

                 <div class="row text-center">
                   <h2 class="section-sub-title title">{{ holding_team.name }}</h2>
                 </div>

                {% for staff in holding_team.staff.all %}
                   <div class="col-xs-12 col-sm-6 col-md-3">
                      {% render_human staff %}
                   </div>
                {% endfor %}

               </div>
               <br><br>
            {% endfor %}

      <!-- Content row 2 end -->
      </div>
      <!--/ Container end -->
   </section>
{% endblock  %}

WSS/templates/WSS/workshops_list.html
{% extends 'wssbase.html' %}
{% load static %}
{% load date_tags %}
{% load human_tags %}

{% block title %}{{ wss }} workshops{% endblock %}
{% block content %}
   <section id="ts-speakers" class="ts-speakers gradient-bg">
      <div class="container">
         <div class="row text-center">
            <h3 class="section-sub-title title-white">{% if wss.workshops.count != 1 %} Workshops {% else %} Workshop {% endif %}</h3>
         </div>

         <!--/ Title row end -->
         <div class="row">
            {% for workshop in wss.workshops %}
             {% if forloop.counter == 1 %}
             <div class="row text-center">
                <h3>For more information about each workshop, click on its image</h3>
             </div>
             {% endif %}

            <div class="col-xs-12 col-sm-6 col-md-3">
                {% render_human workshop.speaker subtitle=workshop.title url=workshop.get_absolute_url %}
                {% if workshop.registration_link %}
                 <p class="text-center">
                    <a href="{{ workshop.registration_link }}" class="btn btn-primary">Register Now</a>
                 </p>
                {% endif %}

            </div>
            {% empty %}
             <div class="row text-center">
                <h3>Nothing has been added yet</h3>
             </div>
            {% endfor %}
         </div>
         <br>

      <!-- Content row 2 end -->

      <!--/ Container end -->
   </section>
   <!-- Workshops end -->
{% endblock %}